create database customer_behaviour_analysis;
use customer_behaviour_analysis; 
alter table customer_shopping_behavior rename to customers;
select * from customers limit 10;

-- 1. What is the total revenue generated by male vs female customers
select gender , sum(purchase_amount) as total_revenue from customers group by gender;

-- 2. Which customers used discount but stil purchased more than the avg purchase amount
select customer_id, purchase_amount from customers where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customers);

-- 3.Top 5 products with the highest average review rating
select item_purchased as Products ,avg(review_rating) as Avg_Review_Rating from customers group by item_purchased order by Avg_Review_Rating desc limit 5;

-- 4. Compare the avg purchase amounts between express and standard shipping modes
select shipping_type , avg(purchase_amount) as Average_purchase_amount  from customers where shipping_type in ("Express","Standard") group by shipping_type;

-- 5. Do subscribed customers spend more? Compare avg spending and total revenue btwn subscribers and non-subscribers
select subscription_status,count(customer_id) as Total_customers, avg(purchase_amount) as Avg_Spending, sum(purchase_amount) as Total_Revenue from customers group by subscription_status;

-- 6. Which 5 products have the highest percentage of purchases with discount applied
select item_purchased, (sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*) )*100 as Discount_Purchase_Percentage 
from customers group by item_purchased order by Discount_Purchase_Percentage desc limit 5;

-- 7. Segment Customers into New,Returning and Loyal based on previous purchases and show the count
with customer_type as ( select customer_id,previous_purchases , 
case 
when previous_purchases = 1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal" end as Customer_Segment from customers
)
select Customer_Segment, count(*) as "Number of customers" from customer_type group by Customer_Segment;

-- 8.What are the three most purchased products in each category
with item_counts as (select item_purchased,category,count(customer_id) as Total_Orders, 
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customers group by item_purchased,category)
select item_rank,item_purchased,category,Total_Orders from item_counts where item_rank <=3;

-- 9.Are customers who are repeat buyers (More than 5) also like to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customers  where previous_purchases >  5 group by subscription_status;

-- 10. What is the revenue generated by each age group?
select  age_group,sum(purchase_amount) as Total_Revenue from customers group by age_group order by Total_Revenue desc; 